### PR TITLE
cansav09/normalization compare

### PR DESCRIPTION
**Pull request by cansavvy**
Main focus of this PR is 1) `asap_data_prep.Rmd`s and 2) `clustering_statistics.Rmd`s

### Scientific question: 
*Which normalization method is best for scRNA-seq?*

This question is evaluated by looking at which normalization methods: 1) Makes cell types cluster together better?  and 2) Makes technical batches cluster together less?

### Methods: 
So far, I've tested this on two datasets: Darmanis (GSE84465) et al, and Arnon et al data (GSE115978). Each have their own "asap_data_prep.Rmd" and their own "clustering_statistics.Rmd". Both of these datasets are human, tumor sample single cell data. Darmanis data is from my own processing pipeline that is being developed and the first~1000 samples that have been finished running (salmon, tximport, etc) and for Arnon et al, I used the counts.csv file the authors supplied on GEO. So note that the datasets are quite different, but for the purposes of answering what normalization method is ideal, I figured this should be fine. 

**Data prep:**
The `asap_data_prep.Rmd` prepares the data in a format that [Automated Single-cell Analysis Pipeline ("ASAP")](https://asap.epfl.ch/) likes. It also applies a filtering step and excludes samples that do not express at least 100 genes and excludes genes that are not expressed in at least 1% of samples. Then, after submitting this formatted counts data to ASAP, 3-5 different normalization methods are tested:  1) DESeq2, 2) log2, 3) scVLM, 4) TMM, 5) voom

The reason that not all 5 methods are tested on both datasets is that some of the methods, DESeq2 and scVLM have troubles if there are too many zeroes or if batch sizes are too small. Because of this practical issue and apparent lack of upkeep on scVLM, these two methods might be excluded from the get go. 

**Clustering Analysis:**
That being said, after normalization methods were run in ASAP, their resulting data were downloaded, and clustering analysis is completed using `clustering_statistics.Rmd` In this script, tSNE clustering is ran and then three types of clustering analysis statistics are obtained (based on Hu & Greene, 2018's analysis and scripts). 

KNN and kmeans clustering are ran over 10 iterations each. KNN clustering is evaluated by the accuracy statistic, and kmeans clustering is evaluated by ARI ("Adjusted Rand Index) and NMI ("Normalized mutual information") statistics. These 3 statistics (ARI, NMI, and KNN accuracy) are then graphed for all normalization methods.

### Remaining questions/concerns:
1) scVLM should work on the Arnon data. Not sure why it complains about 0's when it's literally made for scRNA-seq. That being said, scVLM, from my use of it in R, seems to be mainly tailored to datasets that have batch information. The unfortunate truth is that many authors do not supply batch information and this makes the perk of scVLM not as perky. Not to mention the other problems with it. Basically my point is, scVLM can probably be ruled out because of other concerns. 

2) Batch clustering also seems to increase after normalization methods are ran (at least based on this analysis). Is this a problem with the analysis or a problem with the normalization methods? My guess would be the analysis as it is, is wrong. I am not sure that we should not be supplying the batch info as the predictor since that's not really what we want to be predicted. But I also don't know enough about these methods as of yet to determine what would be an appropriate reconfiguration of this analysis so that it is accurate for batch info clustering. 

3) I could not get KNN to work for Darmanis data at the time being. I believe this is because currently, I have the first 1000 samples ran and some batches are of small sizes, which KNN appears to have a problem with. Once all ~3200 samples are done being processed (I currently have more samples running) this problem should be fixed?? Maybe, hopefully. 

### Preliminary conclusion:
Most likely, even after some tweaks to this analysis, the different normalization methods, will still probably perform about equally. In the event that this is the case, we will most likely go with log2 normalization because of it's ease to apply. This is also what the popular scRNA-seq analysis package, Seurat uses, and it would be nice to have the consistency and "one stop shop" aspect of using one package for all the downstream analyses.

### CODE REVIEW

**Comment by cansavvy** [comment]
darmanis_cell_type_cluster_results
darmanis_plate_batch_cluster_results

**Comment by jaclyn-taroni** [comment]
Can you close this and file a series of ["stacked" pull requests](https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/) please? Looking at the notebooks alone, there are 5 `Rmd` files with at least 100 lines each.

**Comment by cansavvy** [comment]
> Can you close this and file a series of ["stacked" pull requests](https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/) please? Looking at the notebooks alone, there are 5 `Rmd` files with at least 100 lines each.

Will do. I should also mention that asap_data_prep.Rmd and clustering_statistics.Rmd's are essentially the same. I'll split things into smaller chunks though.

**Comment by jaclyn-taroni** [comment]
>  I should also mention that asap_data_prep.Rmd and clustering_statistics.Rmd's are essentially the same. 

I have not looked at these in detail, but does that mean there is a way to consolidate them such that you are not repeating yourself?

**Comment by cansavvy** [comment]
> I have not looked at these in detail, but does that mean there is a way to consolidate them such that you are not repeating yourself?

Perhaps. It all depends on how we want it. The part where the data is actually processing probably could be consolidated. The part with metadata is a bit unavoidable, but I could make that a separate script. My thought was that because this was a one time experiment, it may not make sense to set it up that way. IDK. I could make a set up script for each data set and then make a processing script that is the same.

**Comment by cansavvy** [comment]
If you just want to take a big picture look at one of these script sets for now, and just let me know what you think of the methodology, that would be helpful. Meanwhile, I will reorganize these scripts and submit some different PRs.

**Comment by jaclyn-taroni** [comment]
I took a big picture look at the `asap_data_prep` and `clustering_statistics`. I would make the rounding and filtering for ASAP prep into functions at the very least. The clustering statistics part is probably fine without further refactoring. I would file a PR for the clustering functions R script separately/prior to the clustering status notebooks.

**Comment by cansavvy** [comment]
Sounds good. I will get that to you tomorrow.

**Comment by cansavvy** [comment]
I'm closing this PR so that I can make it into some smaller PRs.

**Pull request closed without merging**
